/**
 * DASHBOARDS
 */
export const TENANT_DASHBOARDS = 'TENANT_DASHBOARDS';
export const TENANT_DASHBOARDS_SUCCESS = 'TENANT_DASHBOARDS_SUCCESS';
export const TENANT_DASHBOARDS_FAILURE = 'TENANT_DASHBOARDS_FAILURE';
export const API_GET_DASHBOARD_SUCCESS = 'API_GET_DASHBOARD_SUCCESS';
export const API_SAVE_DASHBOARD_SUCCESS = 'API_SAVE_DASHBOARD_SUCCESS';
export const API_DELETE_DASHBOARD_SUCCESS = 'API_DELETE_DASHBOARD_SUCCESS';
export const API_GET_SERVERTIME_SUCCESS = 'API_GET_SERVERTIME_SUCCESS';
export const API_ASSIGN_DASHBOARD_CUSTOMER = 'API_ASSIGN_DASHBOARD_CUSTOMER';
export const API_UNASSIGN_DASHBOARD_CUSTOMER = 'API_UNASSIGN_DASHBOARD_CUSTOMER';
export const API_MAKE_PUBLIC_DASHBOARD = 'API_MAKE_PUBLIC_DASHBOARD';
export const CLEAR_DASHBOARDS = 'CLEAR_DASHBOARDS';
