/**
 * DASHBOARDS
 */
export const TENANT_DASHBOARDS = 'TENANT_DASHBOARDS';
export const TENANT_DASHBOARDS_SUCCESS = 'TENANT_DASHBOARDS_SUCCESS';
export const TENANT_DASHBOARDS_FAILURE = 'TENANT_DASHBOARDS_FAILURE';
export const API_GET_DASHBOARD_SUCCESS = 'API_GET_DASHBOARD_SUCCESS';
export const API_SAVE_DASHBOARD_SUCCESS = 'API_SAVE_DASHBOARD_SUCCESS';
export const API_DELETE_DASHBOARD_SUCCESS = 'API_DELETE_DASHBOARD_SUCCESS';
export const CLEAR_DASHBOARDS = 'CLEAR_DASHBOARDS';
