/**
 * PLUGINS
 */
export const API_PLUGINS = 'API_PLUGINS';
export const API_PLUGINS_SUCCESS = 'API_PLUGINS_SUCCESS';
export const API_PLUGINS_FAILURE = 'API_PLUGINS_FAILURE';
export const API_PLUGIN_SAVE_SUCCESS = 'API_PLUGIN_SAVE_SUCCESS';
export const API_PLUGIN_DELETE_SUCCESS = 'API_PLUGIN_DELETE_SUCCESS';
export const API_PLUGIN_SUCCESS = 'API_PLUGIN_SUCCESS';
export const API_PLUGIN_TOKEN_SUCCESS = 'API_SAVE_PLUGIN_SUCCESS';
export const CLEAR_PLUGINS = 'CLEAR_PLUGINS';
