/**
 * AUTHENTICATION
 */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const API_GET_USER_SUCCESS = 'API_GET_USER_SUCCESS';
export const API_GET_USER_FAILURE = 'API_GET_USER_FAILURE';

/**
 * DEVICES
 */
export const TENANT_DEVICES = 'TENANT_DEVICES';
export const TENANT_DEVICES_SUCCESS = 'TENANT_DEVICES_SUCCESS';
export const TENANT_DEVICES_FAILURE = 'TENANT_DEVICES_FAILURE';
export const API_SAVE_DEVICE_SUCCESS = 'API_SAVE_DEVICE_SUCCESS';
export const API_DELETE_DEVICE_SUCCESS = 'API_DELETE_DEVICE_SUCCESS';
export const API_DEVICE_TYPES = 'API_DEVICE_TYPES';
export const API_DEVICE_CREDENTIALS = 'API_DEVICE_CREDENTIALS';

/**
 * DASHBOARDS
 */
export const TENANT_DASHBOARDS = 'TENANT_DASHBOARDS';
export const TENANT_DASHBOARDS_SUCCESS = 'TENANT_DASHBOARDS_SUCCESS';
export const TENANT_DASHBOARDS_FAILURE = 'TENANT_DASHBOARDS_FAILURE';
export const API_SAVE_DASHBOARD_SUCCESS = 'API_SAVE_DASHBOARD_SUCCESS';
export const API_DELETE_DASHBOARD_SUCCESS = 'API_DELETE_DASHBOARD_SUCCESS';

/**
 * RULES
 */
export const API_RULES = 'API_RULES';
export const API_RULES_SUCCESS = 'API_RULES_SUCCESS';
export const API_RULES_FAILURE = 'API_RULES_FAILURE';
export const API_SAVE_RULE_SUCCESS = 'API_SAVE_RULE_SUCCESS';
export const API_DELETE_RULE_SUCCESS = 'API_DELETE_RULE_SUCCESS';

/**
 * PLUGINS
 */
export const API_PLUGINS = 'API_PLUGINS';
export const API_PLUGINS_SUCCESS = 'API_PLUGINS_SUCCESS';
export const API_PLUGINS_FAILURE = 'API_PLUGINS_FAILURE';
export const API_SAVE_PLUGIN_SUCCESS = 'API_SAVE_PLUGIN_SUCCESS';
export const API_DELETE_PLUGIN_SUCCESS = 'API_DELETE_PLUGIN_SUCCESS';

/**
 * CUSTOMERS
 */
export const API_CUSTOMERS = 'API_CUSTOMERS';
export const API_CUSTOMERS_SUCCESS = 'API_CUSTOMERS_SUCCESS';
export const API_CUSTOMERS_FAILURE = 'API_CUSTOMERS_FAILURE';
export const API_SAVE_CUSTOMER_SUCCESS = 'API_SAVE_CUSTOMER_SUCCESS';
export const API_DELETE_CUSTOMER_SUCCESS = 'API_DELETE_CUSTOMER_SUCCESS';

/**
 * CUSTOMERS
 */
export const API_USERS = 'API_USERS';
export const API_USERS_SUCCESS = 'API_USERS_SUCCESS';
export const API_USERS_FAILURE = 'API_USERS_FAILURE';
export const API_SAVE_USERS_SUCCESS = 'API_SAVE_USERS_SUCCESS';
export const API_DELETE_USERS_SUCCESS = 'API_DELETE_USERS_SUCCESS';

/**
 * WIDGETS
 */
export const API_WIDGETS = 'API_WIDGETS';
export const API_WIDGETS_SUCCESS = 'API_WIDGETS_SUCCESS';
export const API_WIDGETS_FAILURE = 'API_WIDGETS_FAILURE';
export const API_SAVE_WIDGET_SUCCESS = 'API_SAVE_WIDGET_SUCCESS';
export const API_DELETE_WIDGET_SUCCESS = 'API_DELETE_WIDGET_SUCCESS';
