/**
 * AUTHENTICATION
 */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/**
 * DEVICES
 */
export const TENANT_DEVICES = 'TENANT_DEVICES';
export const TENANT_DEVICES_SUCCESS = 'TENANT_DEVICES_SUCCESS';
export const TENANT_DEVICES_FAILURE = 'TENANT_DEVICES_FAILURE';

/**
 * DASHBOARDS
 */
export const TENANT_DASHBOARDS = 'TENANT_DASHBOARDS';
export const TENANT_DASHBOARDS_SUCCESS = 'TENANT_DASHBOARDS_SUCCESS';
export const TENANT_DASHBOARDS_FAILURE = 'TENANT_DASHBOARDS_FAILURE';

/**
 * RULES
 */
export const API_RULES = 'API_RULES';
export const API_RULES_SUCCESS = 'API_RULES_SUCCESS';
export const API_RULES_FAILURE = 'API_RULES_FAILURE';

/**
 * PLUGINS
 */
export const API_PLUGINS = 'API_PLUGINS';
export const API_PLUGINS_SUCCESS = 'API_PLUGINS_SUCCESS';
export const API_PLUGINS_FAILURE = 'API_PLUGINS_FAILURE';

/**
 * CUSTOMERS
 */
export const API_CUSTOMERS = 'API_CUSTOMERS';
export const API_CUSTOMERS_SUCCESS = 'API_CUSTOMERS_SUCCESS';
export const API_CUSTOMERS_FAILURE = 'API_CUSTOMERS_FAILURE';

/**
 * WIDGETS
 */
export const API_WIDGETS = 'API_WIDGETS';
export const API_WIDGETS_SUCCESS = 'API_WIDGETS_SUCCESS';
export const API_WIDGETS_FAILURE = 'API_WIDGETS_FAILURE';
