/**
 * WIDGETS
 */
export const API_WIDGETS = 'API_WIDGETS';
export const API_WIDGETS_SUCCESS = 'API_WIDGETS_SUCCESS';
export const API_WIDGETS_FAILURE = 'API_WIDGETS_FAILURE';
export const API_SAVE_WIDGET_SUCCESS = 'API_SAVE_WIDGET_SUCCESS';
export const API_DELETE_WIDGET_SUCCESS = 'API_DELETE_WIDGET_SUCCESS';
export const CLEAR_WIDGETS = 'CLEAR_WIDGETS';
