/**
 * CUSTOMERS
 */
export const API_CUSTOMERS = 'API_CUSTOMERS';
export const API_CUSTOMERS_SUCCESS = 'API_CUSTOMERS_SUCCESS';
export const API_CUSTOMERS_FAILURE = 'API_CUSTOMERS_FAILURE';
export const API_SAVE_CUSTOMER_SUCCESS = 'API_SAVE_CUSTOMER_SUCCESS';
export const API_DELETE_CUSTOMER_SUCCESS = 'API_DELETE_CUSTOMER_SUCCESS';
export const API_CUSTOMERS_SHORT_INFO_SUCCESS = 'API_CUSTOMERS_SHORT_INFO_SUCCESS';
export const CLEAR_CUSTOMERS = 'CLEAR_CUSTOMERS';
