/**
 * USERS
 */
export const API_USERS = 'API_USERS';
export const API_USERS_SUCCESS = 'API_USERS_SUCCESS';
export const API_USERS_FAILURE = 'API_USERS_FAILURE';
export const API_SAVE_USERS_SUCCESS = 'API_SAVE_USERS_SUCCESS';
export const API_DELETE_USERS_SUCCESS = 'API_DELETE_USERS_SUCCESS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const API_SEND_ACTIVATION_SUCCESS = 'API_SEND_ACTIVATION_SUCCESS';
