/**
 * DEVICES
 */
export const TENANT_DEVICES = 'TENANT_DEVICES';
export const TENANT_DEVICES_SUCCESS = 'TENANT_DEVICES_SUCCESS';
export const TENANT_DEVICES_FAILURE = 'TENANT_DEVICES_FAILURE';
export const API_SAVE_DEVICE_SUCCESS = 'API_SAVE_DEVICE_SUCCESS';
export const API_DELETE_DEVICE_SUCCESS = 'API_DELETE_DEVICE_SUCCESS';
export const API_DEVICE_TYPES = 'API_DEVICE_TYPES';
export const API_DEVICE_CREDENTIALS = 'API_DEVICE_CREDENTIALS';
export const API_ASSIGN_DEVICE_TO_CUSTOMER_SUCCESS = 'API_ASSIGN_DEVICE_TO_CUSTOMER_SUCCESS';
export const API_UNASSIGN_DEVICE_TO_CUSTOMER_SUCCESS = 'API_UNASSIGN_DEVICE_TO_CUSTOMER_SUCCESS';
export const API_MAKE_DEVICE_PUBLIC_SUCCESS = 'API_MAKE_DEVICE_PUBLIC_SUCCESS';
export const CLEAR_DEVICES = 'CLEAR_DEVICES';
