/**
 * ADMINS
 */
export const API_ADMINS = 'API_ADMINS';
export const API_ADMINS_SUCCESS = 'API_ADMINS_SUCCESS';
export const API_ADMINS_FAILURE = 'API_ADMINS_FAILURE';
export const API_ADMIN_SETTINGS_SAVE = 'API_ADMIN_SETTINGS_SAVE';
export const CLEAR_ADMINS = 'CLEAR_ADMINS';
