/**
 * RULES
 */
export const API_RULES = 'API_RULES';
export const API_RULES_SUCCESS = 'API_RULES_SUCCESS';
export const API_RULES_FAILURE = 'API_RULES_FAILURE';
export const API_SAVE_RULE_SUCCESS = 'API_SAVE_RULE_SUCCESS';
export const API_SAVE_RULE_FAILURE = 'API_SAVE_RULE_SUCCESS';
export const API_DELETE_RULE_SUCCESS = 'API_DELETE_RULE_SUCCESS';
export const API_DELETE_RULE_FAILURE = 'API_DELETE_RULE_SUCCESS';
export const API_FILTER_COMPONENTS_SUCCESS = 'API_FILTER_COMPONENTS_SUCCESS';
export const API_PROCESSOR_COMPONENTS_SUCCESS = 'API_PROCESSOR_COMPONENTS_SUCCESS';
export const API_PLUGIN_COMPONENTS_SUCCESS = 'API_PLUGIN_COMPONENTS_SUCCESS';
export const API_FILTER_COMPONENT_SUCCESS = 'API_FILTER_COMPONENT_SUCCESS';
export const API_PROCESSOR_COMPONENT_SUCCESS = 'API_PROCESSOR_COMPONENT_SUCCESS';
export const API_PLUGIN_COMPONENT_SUCCESS = 'API_PLUGIN_COMPONENT_SUCCESS';
export const API_ACTION_COMPONENT_SUCCESS = 'API_ACTION_COMPONENT_SUCCESS';
export const API_COMPONENTS_FAILURE = 'API_COMPONENTS_FAILURE';
export const API_RULE_ACTIVATE_SUCCESS = 'API_RULE_ACTIVATE_SUCCESS';
export const API_RULE_ACTIVATE_FAILURE = 'API_RULE_ACTIVATE_FAILURE';
export const CLEAR_RULES = 'CLEAR_CUSTOMERS';
